### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by nanless** [jjunak-yun/FLowHigh_code#1]
Hello, thank you for your great work, I wonder how to find your paper?

**Comment by jjunak-yun** [comment]
Hello @nanless,

Thank you for your interest in our research! Our paper is currently under review. Once it is available on arXiv, we will share the link within this repository.

**Comment by jjunak-yun** [comment]
Hello @nanless ,

Thank you for your patience! We’re happy to share that our paper is now available on arXiv. You can access it through the following link [arXiv](https://arxiv.org/abs/2501.04926).
