### ISSUE TITLE
vocoder chenkpoint

### ISSUE THREAD

**Issue by ivcylc** [jjunak-yun/FLowHigh_code#2]
thanks for your excellent work
could you offer your vocoder checkpoint for inference?

**Comment by jjunak-yun** [comment]
Hello, @ivcylc 

Thank you for being so interested in our research! 
The BIGVGAN generator checkpoint, trained for 850k steps, is at `./vocoder/BIGVGAN/checkpoint/g_48_00850000`.

If you encounter any issues during inference, please let me know!

**Comment by ivcylc** [comment]
Thanks~
